version: '3.1'

services:

  web-app:
    build: Services\WebApp
    container_name: web-app
    ports:
      - "5050:5050"

  account-service:
    build: Services\AccountService
    container_name: account-service
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5051:80"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ai_service_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"



