version: '3.1'

services:

  web-app:
    build: Services\WebApp
    container_name: web-app
    ports:
      - "5050:5050"

  account-service:
    build: Services\AccountService
    container_name: account-service
    ports:
      - "5051:80"
